services:
  web:
    build: .
    container_name: my_app_node
    restart: always
    volumes:
      - .:/usr/src/app/
    ports:
      - "8080:8080"
    command:
      "npm run dev"
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: my_app_psql
    ports:
      - 5432:5432
    env_file:
      - ./.env_db
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
    # command: "node app.js"