name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DEBUG: false
        envkey_SECRET_KEY: ${{ secrets.ENV }}
        file_name: .env
    
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker-compose build
      
      
      
