name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ dev ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      VARIABLE: ${{secrets.VARIABLE}}
      PORT: ${{secrets.PORT}}
      HOST: ${{secrets.HOST}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_HOST: ${{secrets.DB_HOST}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Build instance
        run: docker-compose -f docker-compose.yml build

      - name: Tests
        run: |
          docker-compose -f docker-compose.yml run web npm run db:migrate
          docker-compose -f docker-compose.yml run web npm run db:seed:all
          docker-compose -f docker-compose.yml run web npm run coverage
        
      - name: Linter
        run: docker-compose -f docker-compose.yml run --rm web npm run lint
        
      - name: Tear down the Stack
        run:  docker-compose -f docker-compose.yml down
      
